#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

num1 = 1
num2 = 1
total = 0

#While statement makes sure both numbers are less than 4000000
#If they are, add num1 and num2 to num1
#Then if Num1 is divisible by 2 add Num1 into total
#Repeat this for num2
while num1 < 4000000 and num2 < 4000000:
    num1 = num1 + num2

    if num1 % 2 == 0:
        total = total + num1

    num2 = num1 + num2

    if num2 % 2 == 0:
        total = total + num2

print(total)
